language: php
php:
- '7.2'
sudo: false
branches:
  only:
  - master
#addons:
#  mariadb: '10.2'
env:
# in sequence :
# get the directory name after the sign "-"
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(refname:short)' refs/tags" displays the last tag's shortname
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:subject)' refs/tags" displays the last tag's first line
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:body)' refs/tags" displays the last tag's 3d line and following ones
>
  - GLPI_PLUGIN_NAME=`echo $TRAVIS_BUILD_DIR | sed -e 's/^.*-//'`
    TRAVIS_TAG=`git for-each-ref --sort=-taggerdate --count=1 --format '%(refname:short)' refs/tags`
    RELEASE_NAME=`git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:subject)' refs/tags`
    RELEASE_BODY=`git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:body)' refs/tags`
install: true
script: true
after_success:
- tar --transform "s%^%$GLPI_PLUGIN_NAME/%" --show-transformed -zcvf $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz ajax front inc locales sql *.png *.xml *.php  LICENSE README.md
deploy:
  provider: releases
  api_key:
    secure: RwcK3cht9AtGb9r+6eqijjE5qzIJdA+GTIIN4RokyAU+egt5/uvfCZV4RO61nzZXMvShBHheGp+qj+k3KCiZ+tQAb4J4o+ATirirSfkz0vuof0C0qgoQwGoopw4neupi9wPTQbJiqYCLiodVLFsUmkwyJT6OGKf86nPF8jLmZosRlJ7RrHM3YYMeceErF+N2CpB0niT9L9XBxN8PmpTWODxuB2NQmREP9r24q//VPkgrbC3mFX2BLU3CvhEWbqrC2k+b+dBRbyf5Jfr37qpJGHl4t8hbWOl79FsSo4lTMja+mwVGp2AmBIgfTMZXPIrxGsB63CqCsk8CBUzx9bCSdXa5XJtmda1MwLHNoz+QeoI3BvIyXZn+YqJB/GsgVI+4B7TKQ4I/LehxNaXEfpgCWMqFHDaSzOh9incQkZM0T5uMkNppMPSYEvqK2wFS7jW3oM6L7dzkrJMbIdWcMU98KQcUrer6OrfN9Kg6SxRo22oDiVaaxXr+HgMcmRhIL6aC1mReOsf54ABNsfA5CM8FdRiQCet9PKF1y6GoYBjxOcOZ2505gVEL0I3czgsq9NdpdyOkGI31vSo4UVFwycbexq7j6CQ8nMQziZ/1+PDuCe7yf9JpDMHbtsDerO6c3Cantz/6Hpxp0SZBrxS3z07y/u15dK4JyAA9cXPfScw6JMg=
  skip_cleanup: true
  file: $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz
  name: $RELEASE_NAME
  body: $RELEASE_BODY
  prerelease: false
  on:
    repo: ericferon/glpi-$GLPI_PLUGIN_NAME
    tags: true
